### ISSUE TITLE
Connection timeout

### ISSUE THREAD

**Issue by renkun-ken** [richfitz/redux#51]
Do we have any support for connect with timeout?

The underlying call is quite straightforward:

https://github.com/redis/hiredis/blob/master/examples/example.c#L30

I could file a PR for this.

**Comment by richfitz** [comment]
Hi - yes, I'd be happy to look at a PR for this.  Some quick thoughts on any implementation:

* please make sure to add this through the configuration interface (sorry, I know it's a bit of a mess because of some overly clever bits trying to allow a single URL envvar) so that one could write `redux::redis_config(timeout = 1000)`
* document there why one might want (or need) a timeout and what the timeout refers to

On the latter point - what **does** the timeout refer to?  And what happens when it is exceeded?  Is this a per-request timeout?  One for the server to disconnect the client if it goes stale?  Or just covering the initial connection?

Then, yes, it should be easy to actually wire up the change into the calls to hiredis.

I need to sort out a release to CRAN immediately after the Christmas CRAN closure to deal with the UCRT windows setup, so will be doing a release then; that means if this ends up being nontrivial it might have to wait for the next CRAN update.  I do need to give this package some attention but have had no time since early 2020...

**Comment by renkun-ken** [comment]
Thanks for the reminder!

> what does the timeout refer to? And what happens when it is exceeded? Is this a per-request timeout? One for the server to disconnect the client if it goes stale? Or just covering the initial connection?

The timeout only applies to connect. The currently used `redisConnect` without timeout will block forever under some network condition. If `redisConnectWithTimeout` has timeout, it will result in a `NULL` or a context with `err`.

**Comment by renkun-ken** [comment]
Would you like to take a look at #52 and tell me if there's anything I should change?

**Comment by richfitz** [comment]
Thanks, yes will look soonish - on the face looks fine aside from a few code formatting things. Will have a proper look, but it does look fine to fold into the next release.

Thanks again - will update either tomorrow or early in the new year
